version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: mytestsql_net
    ports:
    - "3306:3306"
    volumes:
      - /d/dockerseries/mysqldata:/var/lib/mysql
    networks:
      - mytestnet
    environment:
      - MYSQL_ROOT_PASSWORD:123
  web:
    image: bilalshahzad139/mysqlnodetest_net
    container_name: mysqlnodetest_net
    ports:
      - "8080:8080"
    networks:
      - mytestnet
    depends_on:
      - db  
networks:
  mytestnet: