FROM mcr.microsoft.com/dotnet/sdk:5.0
EXPOSE 80
EXPOSE 443
EXPOSE 8080
EXPOSE 4443
WORKDIR /source

# COPY *.csproj .
# RUN dotnet restore 

# COPY . . 

# ENTRYPOINT [] (to use base image entry point)

# ENTRYPOINT ["tail", "-f", "/dev/null"] # to keep container running 
